development:
  adapter: postgresql
  encoding: unicode
  database: hogwarts_development
  pool: 5
  username:  dobby
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: hogwarts_test
  pool: 5
  username: dobby
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: hogwarts_production
  pool: 5
  username: dobby
  password:
